athul-7735/green-global-initiative

- green-global-initiative-ui/Dockerfile
- green-global-initiative-ui/angular.json
Creating a Pull request to merge the update in dockerfile to UI branch. As the UI is working through conatiner.
> Feat(UI Update): #NGGI-43 Update Properties of Docker file

- green-global-initiative-ui/src/app/authentication/services/auth.service.ts
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.html
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.scss
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.ts
- green-global-initiative-ui/src/app/grants/grants-routing.module.ts
- green-global-initiative-ui/src/app/grants/services/grants.service.ts
This PR implements the Grant Application Form Page in Angular, following the Figma design guidelines. The form allows 
1. Users to submit grant applications with required fields, 
2. Proper Validation
3. Real-time error handling.
> NGGI-72: Develop grant-application page UI

- green-global-initiative-ui/src/app/app.routes.ts
- green-global-initiative-ui/src/app/contact-us/contactus.component.html
- green-global-initiative-ui/src/app/contact-us/contactus.component.scss
- green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
- green-global-initiative-ui/src/app/contact-us/contactus.component.ts
This PR implements the Contact Page in Angular, following the Figma design guidelines. The page includes 
1.  Contact form with input fields for Name, Email, Subject, and Message
2. Proper validation. 
3. Routing is set up to ensure seamless navigation, and success/error messages are displayed upon form submission.
> NGGI-70: Develop Contact-us page UI

- green-global-initiative-ui/src/app/about-us/about-us.component.html
- green-global-initiative-ui/src/app/about-us/about-us.component.scss
- green-global-initiative-ui/src/app/about-us/about-us.component.spec.ts
- green-global-initiative-ui/src/app/about-us/about-us.component.ts
This PR implements the "About Us" Page in Angular, following the Figma design guidelines. The form allows 
1. User's to view the "About Us" page.
2. Mission, Vision, goals are added
> NGGI-72: Develop and Integrate About Page

- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GrantsApplicationController.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationService.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationServiceImpl.java
This PR introduces a new POST API endpoint to allow users to submit applications to the system. The endpoint follows RESTful principles, validates input data, and ensures secure storage in the backend database.
Key Changes:
Implemented a POST /applications endpoint.
Added input validation to check required fields and enforce correct data formats.
Integrated error handling for invalid requests and database failures.
> NGGI-78: Add POST API for Submitting Grant Applications

- .gitignore
- green-global-initiative-api/init.sql
This PR updates the database initialization file to reflect recent schema changes.
Changes:
Updated SQL queries to match the latest schema design.
> NGGI-81: Update DB Init file

- .github/workflows/SonarQube.yml
- sonar-project.properties
This PR integrates SonarQube with GitHub repositories and sets up SonarLint in Eclipse IDE to enhance code quality and security.
Key Updates:
1. Configured SonarQube for GitHub CI/CD pipelines with automated analysis.
2. Enabled pull request comments with actionable insights.
3. Installed and configured SonarLint in Eclipse for real-time code analysis.
> NGGI - 97 sonar cube sonar lint integration

- green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
- green-global-initiative-ui/src/app/admin/admin-routing.module.ts
- green-global-initiative-ui/src/app/authentication/services/api.service.spec.ts
- green-global-initiative-ui/src/app/authentication/signup/signup.component.html
- green-global-initiative-ui/src/app/authentication/signup/signup.component.scss
- green-global-initiative-ui/src/app/authentication/signup/signup.component.ts
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.ts
- green-global-initiative-ui/src/app/grants/services/grants.service.ts
This PR resolves multiple bugs affecting user experience:
1. Sign-Up Page: Added "Show Password" checkbox for password visibility and fixed account creation errors.
2. About-Us Page: Ensured content loads correctly on page load.
3. My Profile Tab: Added the missing "My Profile" tab to the header for accessibility.
4. Login Page: Fixed issue preventing users from logging in with valid credentials.
> NGGI-104 : Fix identified bugs

- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/GrantsApplicationController.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/dto/ApplicationDetailsDto.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ApplicationDetails.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/ApplicationUpdateRequest.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/GrantsApplicationServiceImpl.java
This PR resolves multiple bugs affecting user experience:
1. My Profile Tab: Added the missing "My Profile" tab to the header for accessibility.
2. Login Page: Fixed issue preventing users from logging in with valid credentials.
> NGGI-104: Bug fix identified during the testing API

- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/controller/QueryController.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/ContactUs.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/model/dao/request/QueryCreateRequest.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ContactUsRepo.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/QueryService.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/service/QueryServiceImpl.java
This PR introduces the backend API for the "Contact Us" page where :
1. enabling users to submit their queries. 
2.  API handles form submissions, performs necessary validations
> NGGI-102: Create api for contact us page

- green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
- green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.html
- green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.spec.ts
- green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
- green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
Added comprehensive unit tests for the  Admin Dashboard Page to validate component rendering, UI interactions, and API integrations. 
Tests cover:
- Admin Dashboard: Page load and content display.
> Feat(Testing): #NGGI-98 Write unit test cases Admin Dashboard Page

- green-global-initiative-ui/src/app/authentication/signup/signup.component.spec.ts
- green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
Added comprehensive unit tests for the Contact us, Authorization and Grants .
Tests cover:
Contact us, Authorization and Grants
> Feat(Testing): #NGGI-103- Write unit test cases part-2

- green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
- green-global-initiative-ui/src/app/contact-us/contactus.component.ts
- green-global-initiative-ui/src/app/contact-us/services/contactus.service.spec.ts
Update the unit testing framework to include the new libraries and to resolve merge conflicts.
> Feat(Testing): #NGGI-98 Update unit test cases.

- .github/workflows/sonar-qube.yml
- green-global-initiative-api/pom.xml
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/DevCorsConfig.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/ApplicationDetailsRepo.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/GrantsRepo.java
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/repository/UserDetailsRepo.java
- green-global-initiative-api/src/test/java/com/atu/green_global_initiative_api/config/DevCorsConfigTest.java
This PR adds comprehensive unit test cases for the backend services.
Changes Implemented:
- Added JUnit test cases using Mockito and Spring Boot Test for service layer and utility classes.
- Achieved 80% coverage in all the class levels.
> NGGI-111: Backend unit testing

- Kubernetes-Manifest-Files/Backend-ingress/backend-ingress.yaml
- Kubernetes-Manifest-Files/Database/secret.yaml
- Kubernetes-Manifest-Files/Frontend-ingress/frontend-ingress.yaml
- Kubernetes-Manifest-Files/frontend/deployment.yaml
- Encrypted secrets in the ingress backend configuration.
- Updated manifest files to securely reference encrypted secrets.
- Verified that encrypted secrets are properly referenced and accessible.
> k8's manifest files update

- green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.spec.ts
- green-global-initiative-ui/src/app/admin/admin-approval/admin-approval.component.ts
- green-global-initiative-ui/src/app/admin/admin-dashboard/admin-dashboard.component.ts
- green-global-initiative-ui/src/app/app.component.spec.ts
- green-global-initiative-ui/src/app/app.component.ts
- green-global-initiative-ui/src/app/authentication/services/api.service.spec.ts
- green-global-initiative-ui/src/app/authentication/services/auth.service.spec.ts
- green-global-initiative-ui/src/app/authentication/signup/signup.component.spec.ts
- green-global-initiative-ui/src/app/contact-us/contactus.component.spec.ts
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.spec.ts
- green-global-initiative-ui/src/app/home/home.component.spec.ts
- green-global-initiative-ui/src/app/shared/guards/auth.guard.spec.ts
- green-global-initiative-ui/src/app/shared/guards/role.guard.spec.ts
- green-global-initiative-ui/src/app/shared/header/header.component.spec.ts
1. Added unit tests for API service, Auth service, and Admin Approval page covering rendering, validation, error handling, and state updates.
2. Updated the architecture diagram to include Prometheus and Grafana.
3. Uploaded the latest diagram to the Teams channel.
> Nggi 114 write unit test cases part 4

- .github/workflows/frondend-ci-cd.yml
- .gitignore
- green-global-initiative-ui/karma.conf.js
- green-global-initiative-ui/package-lock.json
- green-global-initiative-ui/package.json
This PR request is for integrating below task.
- CI Pipeline Implementation – Added a CI YAML file to automate build, test, security scanning, and deployment steps.
- Tool Integration – Integrated Trivy for container security, OWASP Dependency Check for vulnerability detection, and automated unit/integration testing,Synk for vulnerability.
- 
- Testing & Validation – Ensured pipeline failure if code coverage drops below the set threshold and security scans flag critical vulnerabilities.
Thanks,
Siddhartha.
> NGGI-112:CI yaml file integration with all the tools frontend UI

- .github/workflows/Backend-CI-CD.yml
- eks-cluster/module/vpc.tf
This PR updates the system architecture for the Kubernetes cluster setup. It includes revisions to improve scalability, performance, and security, ensuring better resource management and deployment practices. The changes also align with best practices for maintaining a robust and fault-tolerant infrastructure.
> NGGI-122: kubernetes-cluster-setup-system-architecture-revision

- .github/workflows/dependency-check.yml
This PR updates the yaml file for the workflows and updates triggers.
> NGGI-122: Update the CICD workflow

- .github/workflows/frondend-ci-cd.yml
- eks-cluster/eks/backend.tf
This PR does the below things
- Updateing docker hub token key for UI
- Terraform update
> NGGI-124:integration-of-js-doc-ui-V2

- Kubernetes-Manifest-Files/Backend/deployment.yaml
- Kubernetes-Manifest-Files/frontend/deployment.yaml
- green-global-initiative-api/src/main/java/com/atu/green_global_initiative_api/config/SwaggerConfig.java
- green-global-initiative-api/src/main/resources/application-development.properties
- green-global-initiative-api/src/main/resources/application-local.properties
- green-global-initiative-api/src/main/resources/application-production.properties
- green-global-initiative-api/src/main/resources/application.properties
- green-global-initiative-ui/src/app/contact-us/contactus.component.html
- green-global-initiative-ui/src/app/contact-us/contactus.component.ts
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.html
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.scss
- green-global-initiative-ui/src/app/grants/grant-application/grant-application.component.ts
- green-global-initiative-ui/src/app/shared/footer/footer.component.html
- green-global-initiative-ui/src/app/shared/footer/footer.component.ts
- green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.html
- green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.scss
- green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.spec.ts
- green-global-initiative-ui/src/app/shared/popup-window/popup-window.component.ts
This PR adds the fix for the contact us page issue, implements a swagger functionality, and update the popup window in UI.
> NGGI-126: Implement special reward for grants

- Kubernetes-Manifest-Files/Backend/deployment.yaml
- Kubernetes-Manifest-Files/frontend/deployment.yaml
- green-global-initiative-api/docker-compose.yml
This PR adds a CI/CD pipeline YAML configuration for the backend, automating build, test, and deployment stages.
It ensures seamless integration, code quality checks, and deployment to the target environment.
> NGGI-125-implement-cd-pipeline-yaml-configurations-backend

- green-global-initiative-api/docker-compose.yml
- green-global-initiative-ui/Dockerfile
This PR does the below part
- Triggers the workflow file of front end 
- Test the dependency of frontend
> NGGI-120:implement-cd-pipeline-yaml-configurations-front-end_V2

- Kubernetes-Manifest-Files/Backend/deployment.yaml
- Kubernetes-Manifest-Files/frontend/deployment.yaml
- green-global-initiative-api/Dockerfile
- green-global-initiative-ui/Dockerfile
This PR is to test the entire application:
- Frondend pipeline will get triggered
- Backend piepline will get triggered
> NGGI-120:Updating dockerfile to carryout the testing

- green-global-initiative-api/Dockerfile
Updated the backend Dockerfile to include necessary dependencies and configurations for running tests. This ensures that the testing environment is set up correctly.
> NGGI-125:Updating backend dockerfile to carryout the testing 

- Kubernetes-Manifest-Files/Backend/deployment.yaml
- Kubernetes-Manifest-Files/frontend/deployment.yaml
- eks-cluster/eks/dev.tfvars
This PR implements the necessary changes to the backend Terraform module to support Continuous Deployment (CD) pipeline YAML configurations. It updates the module to properly configure and manage Terraform state for the CD pipeline, ensuring smooth integration and deployment processes. Additionally, it adjusts the pipeline YAML to include Terraform initialization and apply steps, enabling automated infrastructure management within the pipeline.
> Nggi 125 implement cd pipeline yaml configurations backend

- .github/workflows/Backend-CI-CD.yml
- .github/workflows/frondend-ci-cd.yml
- green-global-initiative-api/Dockerfile
- green-global-initiative-ui/Dockerfile
This PR does the below task:
- It will trigger the pipeline of frontend and backend 
- cluster is updated to prod
> NGGI-120:implement-cd-pipeline-yaml-configurations-front-end

- Kubernetes-Manifest-Files/frontend/deployment.yaml
- green-global-initiative-api/Dockerfile
- green-global-initiative-ui/Dockerfile
This PR updates the docker files.
> NGGI-126: Update Docker Files
